const MENU_ID='pfFloatingMenu'
const CLUBS_KEY='parfolio-mini:clubs-v1'
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))

function installStyles(){if(document.getElementById('pf-shell-style'))return;const s=document.createElement('style');s.id='pf-shell-style';s.textContent=`
body{padding-top:74px!important}.topbar{display:none!important}.hero-visual{display:none!important}
.pf-floatbar{position:fixed;top:10px;left:50%;transform:translateX(-50%);z-index:12000;width:min(940px,calc(100vw - 20px));height:54px;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:0 10px 0 12px;background:rgba(5,25,18,.92);backdrop-filter:blur(18px);border:1px solid rgba(235,210,123,.25);border-radius:18px;box-shadow:0 14px 40px rgba(0,0,0,.34)}
.pf-floatbrand{display:flex;align-items:center;gap:9px;color:#fff;font-weight:900}.pf-floatbrand img{width:34px;height:34px;object-fit:contain}.pf-floatbrand small{display:block;color:#a8b8b0;font-size:.62rem;font-weight:600;margin-top:1px}.pf-menu-btn{width:42px;height:42px;border:1px solid rgba(255,255,255,.12);border-radius:13px;background:#12352a;color:#fff;font-size:1.25rem}.pf-wallet-mini{font-size:.7rem;color:#efd476;background:rgba(239,212,118,.08);border:1px solid rgba(239,212,118,.2);padding:7px 10px;border-radius:999px;max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.pf-drawer-backdrop{position:fixed;inset:0;z-index:12001;background:rgba(0,0,0,.55);opacity:0;pointer-events:none;transition:.18s}.pf-drawer-backdrop.open{opacity:1;pointer-events:auto}.pf-drawer{position:fixed;z-index:12002;top:0;left:0;bottom:0;width:min(360px,88vw);background:#061d16;color:#fff;transform:translateX(-104%);transition:.22s;padding:calc(18px + env(safe-area-inset-top)) 14px 18px;box-shadow:24px 0 55px rgba(0,0,0,.4);overflow:auto}.pf-drawer.open{transform:none}.pf-drawer-head{display:flex;justify-content:space-between;align-items:center;padding:4px 4px 16px;border-bottom:1px solid rgba(255,255,255,.08)}.pf-drawer-head b{font-size:1.05rem}.pf-drawer-close{width:38px;height:38px;border:0;border-radius:11px;background:#14372c;color:#fff;font-size:1.3rem}.pf-nav-group{padding:12px 0}.pf-nav-label{padding:7px 12px;color:#769187;font-size:.66rem;text-transform:uppercase;letter-spacing:.12em;font-weight:900}.pf-nav-item{width:100%;display:flex;align-items:center;gap:12px;padding:13px 12px;border:0;border-radius:13px;background:transparent;color:#eef4f0;text-align:left;font-size:.92rem;font-weight:750}.pf-nav-item:hover,.pf-nav-item:focus{background:rgba(255,255,255,.06)}.pf-nav-item i{width:26px;text-align:center;color:#eed276;font-style:normal}.pf-nav-item .soon{margin-left:auto;color:#80968c;font-size:.62rem}
.pf-home-intro{margin:0 0 18px;padding:22px;border-radius:24px;border:1px solid rgba(239,211,117,.22);background:radial-gradient(circle at 80% 12%,rgba(240,206,99,.16),transparent 26%),linear-gradient(145deg,#0b3527,#061d16);overflow:hidden}.pf-home-intro h2{margin:4px 0 8px;font:800 clamp(1.8rem,6vw,3.2rem)/.98 Georgia,serif}.pf-home-intro h2 span{color:#efd476}.pf-home-intro p{max-width:760px;color:#b8c8c0;line-height:1.55}.pf-home-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:16px}.pf-home-cards article{min-height:120px;padding:15px;border-radius:16px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.08)}.pf-home-cards b{display:block;color:#efd476;margin-bottom:6px}.pf-home-cards span{font-size:.78rem;color:#b8c7c0;line-height:1.45}.pf-demo-hole{margin-top:16px;border-radius:18px;background:linear-gradient(135deg,#183d2e,#0c271f);border:1px solid rgba(239,211,117,.2);padding:14px;display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.pf-demo-hole strong{font-size:1.05rem}.pf-demo-hole small{display:block;color:#9fb2a8;margin-top:3px}.pf-demo-pot{text-align:right;color:#efd476;font-weight:900;font-size:1.15rem}
.pf-extra-section{margin:22px 0;padding:20px;border-radius:22px;background:#0a2a20;border:1px solid rgba(255,255,255,.08);scroll-margin-top:90px}.pf-extra-section h2{margin:0 0 7px}.pf-extra-section>p{color:#aebeb6;line-height:1.55}.pf-how-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:15px}.pf-how-grid article{padding:14px;border-radius:15px;background:#061e17;border:1px solid rgba(255,255,255,.08)}.pf-how-grid b{display:block;color:#efd476;margin-bottom:5px}.pf-how-grid span{font-size:.76rem;color:#acbdb5;line-height:1.4}.pf-join-row{display:grid;grid-template-columns:1fr auto;gap:8px}.pf-join-row input{min-height:46px;border-radius:12px;border:1px solid rgba(255,255,255,.14);background:#061d16;color:#fff;padding:0 12px;font-size:16px}.pf-join-row button,.pf-action{min-height:46px;border:1px solid rgba(239,211,117,.35);border-radius:12px;background:#e3c86d;color:#102018;padding:0 14px;font-weight:900}.pf-subtle-btn{margin-top:9px;min-height:42px;border-radius:11px;border:1px solid rgba(255,255,255,.14);background:#14372c;color:#fff;padding:0 12px;font-weight:800}.pf-club-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.pf-club-grid label{font-size:.72rem;color:#9fb1a8}.pf-club-grid input{width:100%;margin-top:4px;border:1px solid rgba(255,255,255,.12);border-radius:10px;background:#061d16;color:#fff;padding:9px}.records-section,#verifyRound,.ca-course-finder,.steps-panel,.pf-skins-home{scroll-margin-top:90px}
@media(max-width:720px){.pf-wallet-mini{display:none}.pf-home-cards{grid-template-columns:1fr}.pf-how-grid{grid-template-columns:1fr 1fr}.pf-club-grid{grid-template-columns:1fr 1fr}.pf-home-intro{padding:18px}.pf-floatbar{top:6px}}
@media(max-width:440px){.pf-how-grid{grid-template-columns:1fr}.pf-club-grid{grid-template-columns:1fr}.pf-floatbrand small{display:none}}
`;document.head.appendChild(s)}

function sectionHtml(){return `
<section id="pfHowToPlay" class="pf-extra-section"><p class="eyebrow">How to play ParFolio Skins</p><h2>Every hole can have a reward.</h2><p>Choose the NIM value before the round. Enter each player's score on the hole. Lowest score wins that hole's reward. If the low score is tied, the reward carries forward. At the end, ParFolio totals the results and Nimiq Pay handles the direct player-to-player settlement.</p><div class="pf-how-grid"><article><b>1 · Agree</b><span>Set players and the NIM value per player per hole.</span></article><article><b>2 · Play</b><span>Use GPS, satellite view, yardage and normal ParFolio scoring.</span></article><article><b>3 · Lock</b><span>Confirm each hole's scores so the running reward tally is clear.</span></article><article><b>4 · Settle</b><span>Finish the round and approve any NIM payment directly in Nimiq Pay.</span></article></div></section>
<section id="pfJoinRound" class="pf-extra-section"><p class="eyebrow">Join a group</p><h2>Join with code or QR.</h2><p>Enter the round code shared by the host. On supported devices, you can also scan a QR code with the camera.</p><div class="pf-join-row"><input id="pfJoinCode" maxlength="12" autocomplete="off" placeholder="Enter round code"><button id="pfJoinBtn" type="button">Join</button></div><button id="pfScanQr" class="pf-subtle-btn" type="button">Scan QR code</button><p id="pfJoinStatus" class="helper" role="status"></p></section>
<section id="pfMyClubs" class="pf-extra-section"><p class="eyebrow">ParFolio tools</p><h2>My Clubs</h2><p>Keep quick carry-distance references here. These stay on this device for Mini.</p><div class="pf-club-grid" id="pfClubGrid"></div><button id="pfSaveClubs" class="pf-subtle-btn" type="button">Save club distances</button><p id="pfClubStatus" class="helper"></p></section>`}

function defaultClubs(){return {'Driver':240,'3 Wood':215,'5 Iron':175,'7 Iron':150,'9 Iron':125,'PW':110}}
function renderClubs(){const g=document.querySelector('#pfClubGrid');if(!g)return;let clubs;try{clubs={...defaultClubs(),...JSON.parse(localStorage.getItem(CLUBS_KEY)||'{}')}}catch{clubs=defaultClubs()}g.innerHTML=Object.entries(clubs).map(([name,y])=>`<label>${esc(name)}<input data-club="${esc(name)}" type="number" min="20" max="400" value="${Number(y)||0}"></label>`).join('')}

function closeMenu(){document.querySelector('.pf-drawer')?.classList.remove('open');document.querySelector('.pf-drawer-backdrop')?.classList.remove('open')}
function scrollToTarget(sel){closeMenu();const el=document.querySelector(sel);if(el)el.scrollIntoView({behavior:'smooth',block:'start'})}

function installShell(){installStyles();const app=document.querySelector('#app');if(!app)return
 if(!document.getElementById(MENU_ID)){
  const bar=document.createElement('div');bar.id=MENU_ID;bar.className='pf-floatbar';bar.innerHTML=`<button class="pf-menu-btn" type="button" aria-label="Open menu">☰</button><div class="pf-floatbrand"><img src="/parfolio-mini/parfolio-mini-logo-v2.png" alt=""><span>ParFolio Mini<small>GPS golf · NIM competition</small></span></div><div class="pf-wallet-mini">Nimiq Pay</div>`;document.body.appendChild(bar)
  const back=document.createElement('div');back.className='pf-drawer-backdrop';document.body.appendChild(back)
  const drawer=document.createElement('aside');drawer.className='pf-drawer';drawer.innerHTML=`<div class="pf-drawer-head"><b>ParFolio Mini</b><button class="pf-drawer-close" type="button">×</button></div><div class="pf-nav-group"><div class="pf-nav-label">Play</div><button class="pf-nav-item" data-go="home"><i>⌂</i>Home</button><button class="pf-nav-item" data-go="courses"><i>⌖</i>Courses</button><button class="pf-nav-item" data-go="start"><i>⛳</i>Start a Round</button><button class="pf-nav-item" data-go="join"><i>▦</i>Join with Code / QR</button><button class="pf-nav-item" data-go="how"><i>?</i>How to Play</button></div><div class="pf-nav-group"><div class="pf-nav-label">My ParFolio</div><button class="pf-nav-item" data-go="rounds"><i>≡</i>My Rounds</button><button class="pf-nav-item" data-go="clubs"><i>♢</i>My Clubs</button><button class="pf-nav-item" data-go="wallet"><i>◈</i>Wallet & NIM</button></div><div class="pf-nav-group"><div class="pf-nav-label">About</div><button class="pf-nav-item" data-go="rules"><i>✓</i>Skins Rules</button><button class="pf-nav-item" data-go="settings"><i>⚙</i>Settings</button></div>`;document.body.appendChild(drawer)
  bar.querySelector('.pf-menu-btn').onclick=()=>{drawer.classList.add('open');back.classList.add('open')};drawer.querySelector('.pf-drawer-close').onclick=closeMenu;back.onclick=closeMenu
  drawer.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(!b)return;const m={home:'.hero',courses:'.ca-course-finder',start:'#verifyRound',join:'#pfJoinRound',how:'#pfHowToPlay',rounds:'.records-section',clubs:'#pfMyClubs',wallet:'#connectWallet',rules:'.pf-skins-home',settings:'#pfMyClubs'};scrollToTarget(m[b.dataset.go]||'.hero')})
 }
 const hero=document.querySelector('.hero');if(hero&&!document.querySelector('.pf-home-intro')){const intro=document.createElement('section');intro.className='pf-home-intro';intro.innerHTML=`<p class="eyebrow">ParFolio Mini · Built on the ParFolio golf experience</p><h2>Play smarter. <span>Make every hole matter.</span></h2><p>Use GPS-ready courses, satellite hole views and hole-by-hole scoring just like ParFolio. Add an optional NIM reward to each hole, keep a running tally, and settle directly with your group through Nimiq Pay after the round.</p><div class="pf-home-cards"><article><b>GPS + shot planning</b><span>Validated course geometry, satellite hole view and yardage while you play.</span></article><article><b>Hole-by-hole competition</b><span>Each hole can carry a defined NIM reward. Lowest score wins; ties carry.</span></article><article><b>Wallet-to-wallet settlement</b><span>ParFolio calculates the result. Players approve settlement directly in Nimiq Pay.</span></article></div><div class="pf-demo-hole"><span><strong>Hole 7 · Par 4</strong><small>Rick 4 · Player 2 5 · reward locked</small></span><span class="pf-demo-pot">+2 NIM</span></div>`;hero.parentElement.insertBefore(intro,hero);hero.querySelector('.hero-visual')?.remove()}
 if(!document.querySelector('#pfHowToPlay')){const anchor=document.querySelector('.pf-skins-home')||document.querySelector('.steps-panel')||hero;anchor?.insertAdjacentHTML('afterend',sectionHtml());renderClubs();bindExtras()}
}

function bindExtras(){document.querySelector('#pfJoinBtn')?.addEventListener('click',()=>{const code=document.querySelector('#pfJoinCode').value.trim().toUpperCase();document.querySelector('#pfJoinStatus').textContent=code.length>=4?`Round code ${code} recognized. Live shared-round sync is the next Mini step; your local round tools are ready now.`:'Enter the code from the round host.'})
 document.querySelector('#pfScanQr')?.addEventListener('click',async()=>{const out=document.querySelector('#pfJoinStatus');if(!('BarcodeDetector'in window)){out.textContent='QR camera scanning is not supported in this browser. Enter the round code instead.';return}try{const detector=new BarcodeDetector({formats:['qr_code']});const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const video=document.createElement('video');video.srcObject=stream;video.playsInline=true;await video.play();out.textContent='Point the camera at the round QR code…';let tries=0;const timer=setInterval(async()=>{tries++;const codes=await detector.detect(video).catch(()=>[]);if(codes[0]?.rawValue){clearInterval(timer);stream.getTracks().forEach(t=>t.stop());const raw=codes[0].rawValue;const code=(raw.match(/[?&]join=([^&]+)/i)||[])[1]||raw;document.querySelector('#pfJoinCode').value=decodeURIComponent(code).slice(0,12).toUpperCase();out.textContent='QR code read. Tap Join.'}else if(tries>30){clearInterval(timer);stream.getTracks().forEach(t=>t.stop());out.textContent='No QR code detected. Enter the code instead.'}},250)}catch{out.textContent='Camera access was unavailable. Enter the round code instead.'}})
 document.querySelector('#pfSaveClubs')?.addEventListener('click',()=>{const data={};document.querySelectorAll('[data-club]').forEach(i=>data[i.dataset.club]=Number(i.value)||0);localStorage.setItem(CLUBS_KEY,JSON.stringify(data));document.querySelector('#pfClubStatus').textContent='Club distances saved on this device.'})}

let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;installShell()})}
new MutationObserver(schedule).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});installShell();setTimeout(installShell,300)
